// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkeoUBMpUudBCAXjLaatSKPqf4wgvdylk',
    appId: '1:567323468717:web:a2394b9d61a039de27f724',
    messagingSenderId: '567323468717',
    projectId: 'binemugha-flutter-learning',
    authDomain: 'binemugha-flutter-learning.firebaseapp.com',
    storageBucket: 'binemugha-flutter-learning.appspot.com',
    measurementId: 'G-N6363F5DKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtSVBJLjJLSBNPiT-NGmgCyN7rsLNgP8',
    appId: '1:567323468717:android:e7febaae9bcce08827f724',
    messagingSenderId: '567323468717',
    projectId: 'binemugha-flutter-learning',
    storageBucket: 'binemugha-flutter-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAheQHdDvphPE_2Y_tcr2irteb-YWh3xjE',
    appId: '1:567323468717:ios:29095de276ef5ec827f724',
    messagingSenderId: '567323468717',
    projectId: 'binemugha-flutter-learning',
    storageBucket: 'binemugha-flutter-learning.appspot.com',
    iosBundleId: 'com.example.myBrewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAheQHdDvphPE_2Y_tcr2irteb-YWh3xjE',
    appId: '1:567323468717:ios:29095de276ef5ec827f724',
    messagingSenderId: '567323468717',
    projectId: 'binemugha-flutter-learning',
    storageBucket: 'binemugha-flutter-learning.appspot.com',
    iosBundleId: 'com.example.myBrewCrew',
  );
}
